[bench]
name = "UCI-HAR_CNN+DSOM_int16_evaluate"
seed = 2
first_run = 1
last_run = 15
plugins = ['qualia_plugin_som']

[learningframework]
kind = 'PyTorchDLSOM'

[deploy]
target = 'Linux'
converter.kind = 'QualiaCodeGen'
quantize = ['int16']
optimize = ['']

[dataset]
kind = "UCI_HAR"
params.variant = "raw"
params.path = "data/UCI HAR Dataset/"

[[preprocessing]]
kind = "DatamodelConverter"

[[preprocessing]]
kind = "Class2BinMatrix"

[[postprocessing]]
kind = "QuantizationAwareTraining"
export = true
params.width = 16
params.epochs = 0
params.batch_size = 128
params.model.params.quantize_learning_rate_elasticity = true
params.model.params.quantize_bias       = true
params.model.params.quantize_linear     = true
#params.model.params.quantize_add        = true
#params.force_q = 9

[model_template]
kind = "DLSOM"

#epochs = 0
load = true
train = false

params.dl.kind = "CNN"
#params.dl.epochs = 750
params.dl.epochs = 0 # Do not train DL model
params.dl.load = true # Load pre-trained DL model
params.dl.batch_size = 768
params.dl.name = "uci-har_cnn_20_3-20_3_120"
params.dl.iteration = 1
params.dl.params.filters = [20, 20]
params.dl.params.kernel_sizes = [3, 3]
params.dl.params.fc_units = [120]
params.dl.params.pool_sizes = [2, 0]
params.dl.params.batch_norm = true

params.fm_output = 'relu2'

params.som.epochs = 30
params.som.batch_size = 128
params.som.params.som_layer = "DSOM"

#C6+D1
[[model]]
name = "uci-har_cnn+dsom_c6-5x5"
params.som.params.neurons = [5, 5]
params.som.params.label_sigma = 2.0
params.som.params.learning_rate = 0.0034
params.som.params.elasticity = 0.050
disabled = false

#C6+D2
[[model]]
name = "uci-har_cnn+dsom_c6-6x6"
params.som.params.neurons = [6, 6]
params.som.params.label_sigma = 0.25
params.som.params.learning_rate = 0.0034
params.som.params.elasticity = 0.055
disabled = true

#C6+D3
[[model]]
name = "uci-har_cnn+dsom_c6-7x7"
params.som.params.neurons = [7, 7]
params.som.params.label_sigma = 0.25
params.som.params.learning_rate = 0.0034
params.som.params.elasticity = 0.057
disabled = true

#C6+D4
[[model]]
name = "uci-har_cnn+dsom_c6-8x8"
params.som.params.neurons = [8, 8]
params.som.params.label_sigma = 0.25
params.som.params.learning_rate = 0.0034
params.som.params.elasticity = 0.058
disabled = true

[parameter_research]
params.optimize.params.n_trials = 100
params.study.load = false
params.study.params.direction = "maximize"
params.study.params.study_name = "UCI-HAR_CNN+DSOM_parameter_research2"
params.study.params.storage = "sqlite:///out/parameter_research.sqlite"
params.study.params.load_if_exists = true

[parameter_research.params.trial]
params.som.params.elasticity.kind = 'suggest_float'
params.som.params.elasticity.params.name = 'elasticity'
params.som.params.elasticity.params.low = 0.1
params.som.params.elasticity.params.high = 2.0
params.som.params.learning_rate.kind = 'suggest_float'
params.som.params.learning_rate.params.name = 'learning_rate'
params.som.params.learning_rate.params.low = 0.005
params.som.params.learning_rate.params.high = 0.5
#params.som.params.label_sigma.kind = 'suggest_float'
#params.som.params.label_sigma.params.name = 'label_sigma'
#params.som.params.label_sigma.params.low = 0.1
#params.som.params.label_sigma.params.high = 4.0
#params.som.epochs.kind = 'suggest_int'
#params.som.epochs.params.name = 'epochs'
#params.som.epochs.params.low = 1
#params.som.epochs.params.high = 60
